#include "Instructions.h"
#include "../State.h"

/* 
 * List of all Intel 8080 instructions, in order, with indexes matching opcodes 
 * (0x00 to 0xff).
 */
static struct Instruction8080 list[0xff + 1] = {
	{"NOP",  1, NOP,  {-1}},
	{"LXI",  3, LXI,  {REG_B, -1}},
	{"STAX", 1, STAX, {REG_B, -1}},
	{"INX",  1, INX,  {REG_B, -1}},
	{"INR",  1, INR,  {REG_B, -1}},
	{"DCR",  1, DCR,  {REG_B, -1}},
	{"MVI",  2, MVI,  {REG_B, -1}},
	{"RLC",  1, RLC,  {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"DAD",  1, DAD,  {REG_B, -1}},
	{"LDAX", 1, LDAX, {REG_B, -1}},
	{"DCX",  1, DCX,  {REG_B, -1}},
	{"INR",  1, INR,  {REG_C, -1}},
	{"DCR",  1, DCR,  {REG_C, -1}},
	{"MVI",  2, MVI,  {REG_C, -1}},
	{"RRC",  1, RRC,  {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"LXI",  3, LXI,  {REG_D, -1}},
	{"STAX", 1, STAX, {REG_D, -1}},
	{"INX",  1, INX,  {REG_D, -1}},
	{"INR",  1, INR,  {REG_D, -1}},
	{"DCR",  1, INR,  {REG_D, -1}},
	{"MVI",  2, MVI,  {REG_D, -1}},
	{"RAL",  1, RAL,  {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"DAD",  1, DAD,  {REG_D, -1}},
	{"LDAX", 1, LDAX, {REG_D, -1}},
	{"DCX",  1, DCX,  {REG_D, -1}},
	{"INR",  1, INR,  {REG_E, -1}},
	{"DCR",  1, DCR,  {REG_E, -1}},
	{"MVI",  2, MVI,  {REG_E, -1}},
	{"RAR",  1, RAR,  {-1}},
	{"RIM",  1, NOT_IMPLEMENTED, {-1}}, // Serial I/O (unused)
	{"LXI",  3, LXI,  {REG_H, -1}},
	{"SHLD", 3, SHLD, {-1}},
	{"INX",  1, INX,  {REG_H, -1}},
	{"INR",  1, INR,  {REG_H, -1}},
	{"DCR",  1, DCR,  {REG_H, -1}},
	{"MVI",  2, MVI,  {REG_H, -1}},
	{"DAA",  1, NOT_IMPLEMENTED, {-1}}, // Decimal Adjust Accumulator (unused)
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"DAD",  1, DAD,  {REG_H, -1}},
	{"LHLD", 3, LHLD, {-1}},
	{"DCX",  1, DCX,  {REG_H, -1}},
	{"INR",  1, INR,  {REG_L, -1}},
	{"DCR",  1, DCR,  {REG_L, -1}},
	{"MVI",  2, MVI,  {REG_L, -1}},
	{"CMA",  1, CMA,  {-1}},
	{"SIM",  1, NOT_IMPLEMENTED, {-1}},
	{"LXI",  3, LXI,  {SP, -1}},
	{"STA",  3, NOT_IMPLEMENTED, {-1}}, // TODO
	{"INX",  1, INX,  {SP, -1}},
	{"INR",  1, INR,  {REG_M, -1}},
	{"DCR",  1, DCR,  {REG_M, -1}},
	{"MVI",  2, MVI,  {REG_M, -1}},
	{"STC",  1, STC,  {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"DAD",  1, DAD,  {SP, -1}},
	{"LDA",  2, NOT_IMPLEMENTED,  {-1}}, // TODO
	{"DCX",  1, DCX,  {SP, -1}},
	{"INR",  1, INR,  {REG_A, -1}},
	{"DCR",  1, DCR,  {REG_A, -1}},
	{"MVI",  2, MVI,  {REG_A, -1}},
	{"INX",  1, INX,  {REG_D, -1}},
	{"MOV",  1, MOV,  {REG_B, REG_B}},
	{"MOV",  1, MOV,  {REG_B, REG_C}},
	{"MOV",  1, MOV,  {REG_B, REG_D}},
	{"MOV",  1, MOV,  {REG_B, REG_E}},
	{"MOV",  1, MOV,  {REG_B, REG_H}},
	{"MOV",  1, MOV,  {REG_B, REG_L}},
	{"MOV",  1, MOV,  {REG_B, REG_M}},
	{"MOV",  1, MOV,  {REG_B, REG_A}},
	{"MOV",  1, MOV,  {REG_C, REG_B}},
	{"MOV",  1, MOV,  {REG_C, REG_C}},
	{"MOV",  1, MOV,  {REG_C, REG_D}},
	{"MOV",  1, MOV,  {REG_C, REG_E}},
	{"MOV",  1, MOV,  {REG_C, REG_H}},
	{"MOV",  1, MOV,  {REG_C, REG_L}},
	{"MOV",  1, MOV,  {REG_C, REG_M}},
	{"MOV",  1, MOV,  {REG_C, REG_A}},
	{"MOV",  1, MOV,  {REG_D, REG_B}},
	{"MOV",  1, MOV,  {REG_D, REG_C}},
	{"MOV",  1, MOV,  {REG_D, REG_D}},
	{"MOV",  1, MOV,  {REG_D, REG_E}},
	{"MOV",  1, MOV,  {REG_D, REG_H}},
	{"MOV",  1, MOV,  {REG_D, REG_L}},
	{"MOV",  1, MOV,  {REG_D, REG_M}},
	{"MOV",  1, MOV,  {REG_D, REG_A}},
	{"MOV",  1, MOV,  {REG_E, REG_B}},
	{"MOV",  1, MOV,  {REG_E, REG_C}},
	{"MOV",  1, MOV,  {REG_E, REG_D}},
	{"MOV",  1, MOV,  {REG_E, REG_E}},
	{"MOV",  1, MOV,  {REG_E, REG_H}},
	{"MOV",  1, MOV,  {REG_E, REG_L}},
	{"MOV",  1, MOV,  {REG_E, REG_M}},
	{"MOV",  1, MOV,  {REG_E, REG_A}},
	{"MOV",  1, MOV,  {REG_H, REG_B}},
	{"MOV",  1, MOV,  {REG_H, REG_C}},
	{"MOV",  1, MOV,  {REG_H, REG_D}},
	{"MOV",  1, MOV,  {REG_H, REG_E}},
	{"MOV",  1, MOV,  {REG_H, REG_H}},
	{"MOV",  1, MOV,  {REG_H, REG_L}},
	{"MOV",  1, MOV,  {REG_H, REG_M}},
	{"MOV",  1, MOV,  {REG_H, REG_A}},
	{"MOV",  1, MOV,  {REG_L, REG_B}},
	{"MOV",  1, MOV,  {REG_L, REG_C}},
	{"MOV",  1, MOV,  {REG_L, REG_D}},
	{"MOV",  1, MOV,  {REG_L, REG_E}},
	{"MOV",  1, MOV,  {REG_L, REG_H}},
	{"MOV",  1, MOV,  {REG_L, REG_L}},
	{"MOV",  1, MOV,  {REG_L, REG_M}},
	{"MOV",  1, MOV,  {REG_L, REG_A}},
	{"MOV",  1, MOV,  {REG_M, REG_B}},
	{"MOV",  1, MOV,  {REG_M, REG_C}},
	{"MOV",  1, MOV,  {REG_M, REG_D}},
	{"MOV",  1, MOV,  {REG_M, REG_E}},
	{"MOV",  1, MOV,  {REG_M, REG_H}},
	{"MOV",  1, MOV,  {REG_M, REG_L}},
    {"HLT",  1, HLT,  {-1}},
	{"MOV",	 1, MOV,  {REG_M, REG_A}},
	{"MOV",	 1, MOV,  {REG_A, REG_B}},
	{"MOV",	 1, MOV,  {REG_A, REG_C}},
	{"MOV",	 1, MOV,  {REG_A, REG_D}},
	{"MOV",	 1, MOV,  {REG_A, REG_E}},
	{"MOV",	 1, MOV,  {REG_A, REG_H}},
	{"MOV",	 1, MOV,  {REG_A, REG_L}},
	{"MOV",	 1, MOV,  {REG_A, REG_M}},
	{"MOV",	 1, MOV,  {REG_A, REG_A}},
	{"ADD",  1, ADD,  {REG_B}},
	{"ADD",  1, ADD,  {REG_C}},
	{"ADD",  1, ADD,  {REG_D}},
	{"ADD",  1, ADD,  {REG_E}},
	{"ADD",  1, ADD,  {REG_H}},
	{"ADD",  1, ADD,  {REG_L}},
	{"ADD",  1, ADD,  {REG_M}},
	{"ADD",  1, ADD,  {REG_A}},
	{"ADC",  1, ADC,  {REG_B}},
	{"ADC",  1, ADC,  {REG_C}},
	{"ADC",  1, ADC,  {REG_D}},
	{"ADC",  1, ADC,  {REG_E}},
	{"ADC",  1, ADC,  {REG_H}},
	{"ADC",  1, ADC,  {REG_L}},
	{"ADC",  1, ADC,  {REG_M}},
	{"ADC",  1, ADC,  {REG_A}},
	{"SUB",  1, SUB,  {REG_B}},
	{"SUB",  1, SUB,  {REG_C}},
	{"SUB",  1, SUB,  {REG_D}},
	{"SUB",  1, SUB,  {REG_E}},
	{"SUB",  1, SUB,  {REG_H}},
	{"SUB",  1, SUB,  {REG_L}},
	{"SUB",  1, SUB,  {REG_M}},
	{"SUB",  1, SUB,  {REG_A}},
	{"SBB",  1, SBB,  {REG_B}},
	{"SBB",  1, SBB,  {REG_C}},
	{"SBB",  1, SBB,  {REG_D}},
	{"SBB",  1, SBB,  {REG_E}},
	{"SBB",  1, SBB,  {REG_H}},
	{"SBB",  1, SBB,  {REG_L}},
	{"SBB",  1, SBB,  {REG_M}},
	{"SBB",  1, SBB,  {REG_A}},
	{"ANA",  1, ANA,  {REG_B}},
	{"ANA",  1, ANA,  {REG_C}},
	{"ANA",  1, ANA,  {REG_D}},
	{"ANA",  1, ANA,  {REG_E}},
	{"ANA",  1, ANA,  {REG_H}},
	{"ANA",  1, ANA,  {REG_L}},
	{"ANA",  1, ANA,  {REG_M}},
	{"ANA",  1, ANA,  {REG_A}},
	{"XRA",  1, XRA,  {REG_B}},
	{"XRA",  1, XRA,  {REG_C}},
	{"XRA",  1, XRA,  {REG_D}},
	{"XRA",  1, XRA,  {REG_E}},
	{"XRA",  1, XRA,  {REG_H}},
	{"XRA",  1, XRA,  {REG_L}},
	{"XRA",  1, XRA,  {REG_M}},
	{"XRA",  1, XRA,  {REG_A}},
	{"ORA",  1, ORA,  {REG_B}},
	{"ORA",  1, ORA,  {REG_C}},
	{"ORA",  1, ORA,  {REG_D}},
	{"ORA",  1, ORA,  {REG_E}},
	{"ORA",  1, ORA,  {REG_H}},
	{"ORA",  1, ORA,  {REG_L}},
	{"ORA",  1, ORA,  {REG_M}},
	{"ORA",  1, ORA,  {REG_A}},
	{"CMP",  1, CMP,  {REG_B}},
	{"CMP",  1, CMP,  {REG_C}},
	{"CMP",  1, CMP,  {REG_D}},
	{"CMP",  1, CMP,  {REG_E}},
	{"CMP",  1, CMP,  {REG_H}},
	{"CMP",  1, CMP,  {REG_L}},
	{"CMP",  1, CMP,  {REG_M}},
	{"CMP",  1, CMP,  {REG_A}},
	{"RNZ",  1, RNZ,  {-1}},
	{"POP",  1, POP,  {REG_B, -1}},
	{"JNZ",  3, JNZ,  {-1}},
	{"JMP",  3, JMP,  {-1}},
	{"CNZ",  3, CNZ,  {-1}},
	{"PUSH", 1, PUSH, {REG_B, -1}},
	{"ADI",  2, ADI,  {-1}},
	{"RST",  1, RST,  {0, -1}}, // TODO
	{"RZ",   1, RZ,   {-1}},
	{"RET",  1, RET,  {-1}},
	{"JZ",   3, JZ,   {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"CZ",   3, CZ,   {-1}},
	{"CALL", 3, CALL, {-1}},
	{"ACI",  2, ACI,  {-1}},
	{"RST",  1, RST,  {1, -1}},
	{"RNC",  1, RNC,  {-1}},
	{"POP",  1, POP,  {REG_D, -1}},
	{"JNC",  3, JNC,  {-1}},
	{"OUT",  2, OUT,  {-1}},
	{"CNC",  3, CNC,  {-1}},
	{"PUSH", 1, PUSH, {REG_D, -1}},
	{"SUI",  2, SUI,  {-1}},
	{"RST",  1, RST,  {2, -1}},
	{"RC",   1, RC,   {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"JC",   3, JC,   {-1}},
	{"IN",   2, IN,   {-1}},
	{"CC",   3, CC,   {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"SBI",  2, SBI,  {-1}},
	{"RST",  1, RST,  {3, -1}},
	{"RPO",  1, RPO,  {-1}},
	{"POP",  1, POP,  {REG_H, -1}},
	{"JPO",  3, JPO,  {-1}},
	{"XTHL", 1, XTHL, {-1}},
	{"CPO",  3, CPO,  {-1}},
	{"PUSH", 1, PUSH, {REG_H, -1}},
	{"ANI",  2, ANI,  {-1}},
	{"RST",  1, RST,  {4, -1}},
	{"RPE",  1, RPE,  {-1}},
	{"PCHL", 1, NOT_IMPLEMENTED, {-1}}, // TODO
	{"JPE",  3, JPE,  {-1}},
	{"XCHG", 1, NOT_IMPLEMENTED, {-1}}, // TODO
	{"CPE",  3, CPE,  {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
	{"XRI",  1, XRI,  {-1}},
	{"RST",  1, RST,  {5, -1}},
	{"RP",   1, RP,   {-1}},
	{"POP",  1, POP,  {PSW, -1}},
	{"JP",   3, JP,   {-1}},
	{"DI",   1, DI,   {-1}},
	{"CP",   3, CP,   {-1}},
	{"PUSH", 1, PUSH, {PSW, -1}},
	{"ORI",  2, ORI,  {-1}},
	{"RST",  1, RST,  {6, -1}},
	{"RM",   1, RM,   {-1}},
	{"SPHL", 1, SPHL, {-1}},
	{"JM",   3, JM,   {-1}},
	{"EI",   1, EI,   {-1}},
	{"CM",   3, CM,   {-1}},
	{"-",    1, NOT_IMPLEMENTED, {-1}},
    {"CPI",  2, NOT_IMPLEMENTED, {-1}}, // TODO
	{"RST",  1, RST,  {7, -1}}
};

// Get instruction with matching opcode (0x00 through 0xff)
Instruction8080 *Get_Instruction(uint8_t instruction)
{
	return &list[instruction];
}